In [5]:
import json
import gzip
import pandas as pd
import numpy as np

In [6]:
rows = []
import ast
with open("../datasets/australian_users_items.json", encoding='MacRoman') as f:
    # Leer cada línea del archivo.
    for line in f.readlines():
        # Utilizar "ast.literal_eval" para convertir cada línea en un diccionario de Python
        # y agregarlo a la lista "rows".
        rows.append(ast.literal_eval(line))

df_user_items = pd.DataFrame(rows)
df_user_items.head()

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,76561197963445855,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea..."

In [7]:
df_user_items_final = df_user_items.drop(["steam_id", "user_url"], axis=1)

In [8]:
df_user_items_final.to_csv('df_user_items_clean.csv.gz', sep=',' , index=False, compression= "gzip")

In [25]:
df_user_items_clean = pd.read_csv('df_user_items_clean.csv')

In [26]:
df_user_items_clean

,user_id,items_count,items
0,76561197970982479,277,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,"[{'item_id': '300', 'item_name': 'Day of Defea..."
...,...,...,...
88305,76561198323066619,22,"[{'item_id': '413850', 'item_name': 'CS:GO Pla..."
88306,76561198326700687,177,"[{'item_id': '11020', 'item_name': 'TrackMania..."
88307,XxLaughingJackClown77xX,0,[]
88308,76561198329548331,7,"[{'item_id': '304930', 'item_name': 'Unturned'..."
88309,edward_tremethick,0,[]

In [12]:
#Asegurándonos de que las columnas 'genres' y 'tags' sean de tipo string
#df_steam_games['genres'] = df_steam_games['genres'].astype(str)
#df_steam_games['tags'] = df_steam_games['tags'].astype(str)

#Concatenando las columnas 'genres' y 'tags'
#df_steam_games['genres'] = df_steam_games['genres'] + ', ' + df_steam_games['tags']

#Eliminando duplicados
#df_steam_games['genres'] = df_steam_games['genres'].apply(lambda x: ', '.join(set(x.split(', '))))

In [13]:
#con fill na
#df_steam_games['genres'].fillna(df_steam_games['tags'], inplace=True)

In [14]:
#df_user_items['playtime_forever'] = df_user_items['items'].apply(lambda x: x[0].get('playtime_forever') if len(x) > 0 else 0)
#df_user_items['playtime_forever'] = df_user_items['playtime_forever'].astype(int)
#df_user_items['item_id'] = df_user_items['items'].apply(lambda x: x[0].get('item_id') if len(x) > 0 else 0)